Sprint1
oier-elorrieta/R3-ASIER-JONM-JONV-DDBB pull request #1
Opened 2021-01-27 09:37 UTC by JonM-elorrieta

2021-01-27 09:42 UTC, Jose-Elorrieta commented
El esquema E-R y el paso a tablas, uno de los dos atributos que hacen referencia al total de la operación sobra. Yo eliminaría también el atributo NumUniVendidas de Productos. Creo que no aporta nada.
Si revisáis las tablas del modelo lógico, hay una tabla que no está en 3FN. Esto ya es para nivel ‘avanzado’, pero estaría bien que lo detectarais.
En cuanto al diseño físico:
-	Al crear la base de datos es muy aconsejable asignarle un cotejamiento para que no haya problemas con caracteres propios del español (letras con tildes, palabras con ñ, etc.).
-	Para cadenas de caracteres hay los tipos char y varchar. Usad char en algunos casos en aquellos casos en los que el campo sea de longitud fija.
-	Para atributos con dominios finitos (pocos valores posibles) hay un tipo de dato en MySQL que se puede utilizar. Ya lo habéis usado para el atributo DomicilioSioNo de Pedido, pero se puede usar en más casos. 
-	En los atributos clave ajena no se puede poner la propiedad auto_increment. Solo se puede asignar a atributos clave primaria.
-	En la tabla Aparecen al atributo ID es mejor llamarlo de manera que se sepa aquello a lo que se refiere, por ejemplo, con IDOperación o algo así.

Como veis, está bastante bien, por lo que tenéis tiempo para hacer las correcciones antes de la demo. En cuanto estén hechas las correcciones, enviadme un email, por favor.

2021-01-30 11:32 UTC, Jose-Elorrieta requested changes
Habéis incorporado los cambio solicitados menos la eliminación del atributo NumUnidadesVendidas de producto. ¿Para qué sirve este atributo? Para saber el nº de unidades vendidas por producto en total. Yo creo que no hace falta, pero ya veréis, pero si lo mantenéis lo tendréis que ir actualizando cada vez que se haga una venta.

Hay una tabla, que es la tabla Factura que no está en 3FN. Pensad, por favor, cómo pasarla a 3FN, lo que dará lugar a una nueva tabla. Repasad para esto la teoría de la normalización si no os acordáis.

2021-02-01 08:28 UTC, JonM-elorrieta commented
Cambios realizados

2021-02-01 14:58 UTC, Jose-Elorrieta approved these changes
De acuerdo. Os doy el visto bueno. El paso a 3FN también se podría haber hecho de otra forma. Os lo comento en clase el miércoles.

2021-02-01 15:51 UTC, merged